Assorted numpy Constructors
-----------------------------

In [2]:
#Always need to import it... 
import numpy as np

## The ones you will most commonly use

Making arrays from scratch

```
zeros()
ones()
linspace()
```
Or from existing data stracutures:
```
array()
```

In [5]:
# from scratch:
a = np.ones((3,2)) # default dtype is float64
a

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [6]:
print(a.dtype)


float64


In [7]:
print(np.zeros((2,3), dtype=np.int32))

[[0 0 0]
 [0 0 0]]


In [8]:
print (np.empty((3,3), dtype=np.float32)) # not initilized!

[[  0.00000000e+00  -2.52435490e-29   3.57649012e-29]
 [  8.58993459e+09   9.40395929e-38   1.40129846e-45]
 [  3.60225631e-39   1.40129846e-45   3.60225631e-39]]


In [9]:
# for a range:
# integers (much like the regular range...)
print(np.arange(2, 20, 2))

[ 2  4  6  8 10 12 14 16 18]


In [13]:
# for floats
# from zero to 1  (inclusive)
# you want 11 total elements
print(np.linspace(0, 1, 11))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [14]:
# you can do arange with floats, too
# but it can get wierd with floating point error!
print(np.arange(0,1.1, 0.1, dtype=np.float))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [15]:
# if you are a math/scicnce geek, and want a log axis...
print(np.logspace(0, 3, 4))

[    1.    10.   100.  1000.]


## From existing data:
```
array()
asarray()
```

In [19]:

# maybe the most common constructor 
a = np.array([(1, 2),
                (3, 4, 5),
                (5, 6)]) # auto-determined dtype
print(a)

[(1, 2) (3, 4, 5) (5, 6)]


In [21]:
a.shape, a.dtype

((3,), dtype('O'))

In [23]:
# maybe an array?
a = np.arange(5)
b = np.asarray(a)
print(a is b)

True


In [24]:
# or not:
a = range(5)
b = np.asarray(a)
print(a is b)

False


In [25]:
print(np.ascontiguousarray(a))# forces contiguous datablock

[0 1 2 3 4]


In [26]:
# from binary data:
s = b'abcdefg'
a = np.frombuffer(s, dtype=np.uint8)
print(a)

[ 97  98  99 100 101 102 103]


In [27]:
# "fromstring" is named from py2 when a string was a string of bytes
# you really want to use a bytes object here, not a string.
print(np.fromstring(b'\x12\x04', dtype=np.uint8))

[18  4]


In [28]:
# from (and to) binary file:
a = np.arange(5, dtype=np.float32) # jsut a binary dump!
a.tofile('junk.dat')

In [29]:
# to read raw binary data you need the dtype.
# if you get it wrong, you get junk:
print(np.fromfile('junk.dat', dtype=np.int32))

[         0 1065353216 1073741824 1077936128 1082130432]


In [30]:
# this works better
print(np.fromfile('junk.dat', dtype=np.float32))

[ 0.  1.  2.  3.  4.]
