# Fancy Indexing


Fancy indexing is the name for when an array or list is used inplace of an index:

In [1]:
import numpy as np

In [2]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

As we've seen, numpy extends the regular python slicing syntax to make it easy to pull our regtangular blocks from arrays:

In [3]:
A[2:4, 1:3]

array([[21, 22],
       [31, 32]])

But what if you want a subset of the array that is not a contiguous rectangular block? Enter Fancy Indexing.

There are two types of fancy indexing: boolean arrays, and index arrays.

### Boolean arrays

Boolean arrays let you pull out a subset of an array with a boolean "mask"

In [4]:
a = np.random.random_integers(0, 20, 7)
a

array([ 4, 10, 15,  0,  9, 10, 20])

In [5]:
# create a boolean mask
mask = np.array([True, False, True, False, False, False, True])

# index with that mask -- you get the elements where the mask is true
a[mask]

array([ 4, 15, 20])

But why is this useful? -- because we can create the mask with logical operations:

In [6]:
mask = a > 8
mask

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

And you can assign to the sub-array, too -- very handy:

Set all the values greater than 8 to 8:

In [7]:
a[a > 8] = 8
a

array([4, 8, 8, 0, 8, 8, 8])

### array indexing

But what if you know the indexes of the elements you want?

you can pass those in:

In [8]:
a[ [1, 3, 2, 3] ] # note that you can repeat the same index...

array([8, 0, 8, 0])

In [9]:
# and it can work on higher rank arrays, also:
row_indices = [0, 2, 3]
A[row_indices]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [10]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([ 1, 22, 34])

## Functions and methods for extracting data from arrays

(these pre-date fancy indexing, and thus are less used. but sometimes the best way to do it)

### where
The index mask can be converted to position index using the where function

In [12]:
indices = np.where(mask)
indices

(array([1, 2, 4, 5, 6]),)

In [13]:
x = np.random.rand(8)
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([ 0.85078687,  0.40800382,  0.32703315,  0.64197836,  0.30596153])

But `where()` does more:

`where(condition, [x, y])`

Return elements, either from `x` or `y`, depending on `condition`.

In [14]:
x

array([ 0.75489954,  0.85078687,  0.40800382,  0.10192573,  0.32703315,
        0.64197836,  0.30596153,  0.51362076])

In [15]:
np.where( x < 0.7, 0, [1,2,3,4,5,6,7,8])

array([1, 2, 0, 0, 0, 0, 0, 0])

In [17]:
A = np.arange(20).reshape((4,5))
print(A)
mask1 = (A > 10).astype(np.uint8)
print(mask1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 1]
 [1 1 1 1 1]]


In [18]:
mask2 = (A < 12).astype(np.uint8)
print(mask2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 0]
 [0 0 0 0 0]]


In [19]:
print(mask1 + mask2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 2 1 1 1]
 [1 1 1 1 1]]


In [ ]:
print(np.where(A > 10, 1, 0))

### diag
With the diag function we can also extract the diagonal and subdiagonals of an array:

In [20]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
np.diag(A)

array([ 0,  6, 12, 18])

In [22]:
# you can get the diagonals that are not the main ones
np.diag(A, -1)

array([ 5, 11, 17])

In [23]:
np.diag(A, 1)

array([ 1,  7, 13, 19])

### take
The take function is similar to fancy indexing described above

`np.take(a, indices, axis=None, out=None, mode='raise')`

Take elements from an array along an axis.

This function does the same thing as "fancy" indexing (indexing arrays
using arrays); however, it can be easier to use if you need elements
along a given axis.

In [24]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Let's say we want the 0,2,3 rows.
Easy with "fancy indexing"

In [25]:
A[ [0,2,3] ]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

But what if we want the 0,2,3 columns?

`take` makes that easy

In [26]:
A.take([0,2,3], axis=1)

array([[ 0,  2,  3],
       [ 5,  7,  8],
       [10, 12, 13],
       [15, 17, 18]])

In [27]:
A.take([0,2,3], axis=0) # zero is the default axis

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
A[ [0,2,3] ]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

`take` is also a function (not method), and so works on lists and other objects:

In [29]:
np.take([-3, -2, -1,  0,  1,  2], row_indices)

array([-3, -1,  0])

## Choose
Constructs an array by picking elements from several arrays:

In [31]:
which = [1, 0, 2, 1]
# we are choosing from three different arrays:
#  0, 1, 2
# so you need to pass in three arrays
choices = [[-2,-2,-2,-2],
           [5,  5, 5, 5],
           [7, 7, 7, 7]]

np.choose(which, choices)
# what shape will the result be?
# hint: all arrays must be the same size

array([ 5, -2,  7,  5])

This one is pretty tricky -- but handy when you need it.