Intro to numpy memory use and structure
-----------------------------------------

In [1]:
import sys
# Always use this import line!
import numpy as np
# handy utility for printing numpy array description.
from start import print_info

In [3]:
empty_list = sys.getsizeof([])
print("size of empty list:", empty_list)

size of empty list: 64


In [4]:
empty_array = sys.getsizeof(np.array([]))
print("size of empty ndarray:", empty_array)

size of empty ndarray: 96


In [5]:
py_float = sys.getsizeof(1.0)
print("size of python float:", py_float)

size of python float: 24


In [7]:
numpy_float = np.array(1.0).itemsize
print("size of numpy float64:", numpy_float)

size of numpy float64: 8


In [8]:
print("A 1000 element list of floats:")
print(empty_list + 1000*8 + 1000*py_float, 'bytes')

A 1000 element list of floats:
32064 bytes


In [9]:
print("A 1000 element list of floats:")
print(empty_array + 1000*numpy_float, 'bytes')

A 1000 element list of floats:
8096 bytes


Demo of the underlying structure:
-----------------------------------    

In [10]:
# create an array:
a = np.arange(12)
print_info(a)

arr :
[ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.shape: (12,)
arr.dtype: int64
arr.itemsize 8
arr.ndim: 1
arr.strides (8,)
arr.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [11]:
# reshape it
a.shape = (3,4)
print_info(a)

arr :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr.shape: (3, 4)
arr.dtype: int64
arr.itemsize 8
arr.ndim: 2
arr.strides (32, 8)
arr.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [12]:
# transpose it
b = a.transpose()
print_info(b) 

arr :
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
arr.shape: (4, 3)
arr.dtype: int64
arr.itemsize 8
arr.ndim: 2
arr.strides (8, 32)
arr.flags:
   C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [15]:
# reshape again
a.shape = (2,2,3)
print_info(a)

arr :
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
arr.shape: (2, 2, 3)
arr.dtype: int64
arr.itemsize 8
arr.ndim: 3
arr.strides (48, 24, 8)
arr.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [16]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [18]:
# take a slice:
s = a[:,1,:]
print_info(s)

arr :
[[ 3  4  5]
 [ 9 10 11]]
arr.shape: (2, 3)
arr.dtype: int64
arr.itemsize 8
arr.ndim: 2
arr.strides (48, 8)
arr.flags:
   C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
