In [27]:
import numpy as np
from start import *

Reshaping

In [28]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
a.shape

(12,)

In [30]:
b = np.reshape(a, (3,4) )
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
b is a

False

In [32]:
# unknown dimension
# -1 will be replaced by whatever is needed to make it fit.
a.shape = ( -1, 2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [33]:
# flatten
for i in a.flat: # iterator
    print(i) 

0
1
2
3
4
5
6
7
8
9
10
11


In [34]:
# ravel creates a new array with a view onto the same data 
# oddly enough, means that same thing as unravel....
b = np.ravel(a)
b is a
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
print(a.shape)
print(a.T) # Transpose -- swap dimensions


(6, 2)
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [36]:
a.T.copy().ravel()

array([ 0,  2,  4,  6,  8, 10,  1,  3,  5,  7,  9, 11])

In [37]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

Checking dimensions:

In [38]:
a = np.atleast_2d(a)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
a.shape

(6, 2)

In [40]:
# reducing the number of dimensions:
a.shape = (2,1,1,6,1)
a.shape

(2, 1, 1, 6, 1)

In [41]:
b = np.squeeze(a)
b.shape

(2, 6)

In [42]:
# re-arranging:
print(b)
print(np.flipud(b)) # flip up-down

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [43]:
print(np.fliplr(b)) # flip left-right

[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]]
