In [1]:
import numpy as np
from start import *

Reshaping

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a.shape

(12,)

In [5]:
b = np.reshape(a, (3,4) )
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
b is a

False

In [7]:
# unknown dimension
# -1 will be replaced by whatever is needed to make it fit.
a.shape = ( -1, 2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [9]:
# flatten
for i in a.flat: # iterator
    print(i) 
print(a.flat)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
# ravel creates a new array with a view onto the same data 
# oddly enough, means that same thing as unravel....
b = np.ravel(a)
b is a
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
print(a.shape)
print(a.T) # Transpose -- swap dimensions
print(a.T.shape)


(6, 2)
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
(2, 6)


In [13]:
a.T.copy().ravel()

array([ 0,  2,  4,  6,  8, 10,  1,  3,  5,  7,  9, 11])

In [37]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

Checking dimensions:

In [14]:
a = np.atleast_2d(a)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
a.shape

(6, 2)

In [19]:
np.atleast_2d(np.ones((3,))).shape

(1, 3)

In [20]:
# reducing the number of dimensions:
a.shape = (2,1,1,6,1)
a.shape

(2, 1, 1, 6, 1)

In [22]:
b = np.squeeze(a)
b.shape

(2, 6)

In [23]:
# re-arranging:
print(b)
print(np.flipud(b)) # flip up-down

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [24]:
print(np.fliplr(b)) # flip left-right

[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]]
