numpy slicing demo
--------------------

In [1]:
import numpy as np
from start import print_info

## Slicing is much like regular python sequences

Very much the same in 1-d

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#indexing
print(a[3])

# slicing
print(a[3:6])

3
[3 4 5]


Look familar?

Now for 2-d

In [5]:
# create a 2d array:
a = np.arange(20).reshape((4,5)) # note the nifty reshape!
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
#index in 2-d:
a[1, 2] # row 1, column 2   

7

In [7]:
# slices get you a rectangular block

a[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

## Indexing reduces rank..

(rank is numpy-spek for the number of dimensions)

In [8]:
a.shape

(4, 5)

In [10]:
r = a[2] # pulls out a row
print(r)
print(r.shape)

[10 11 12 13 14]
(5,)


In [12]:
# now 1-d
# pulling our a column
c = a[:,2] # all rows, column 2
print(c)
print(c.shape)

[ 2  7 12 17]
(4,)


Note that that is a 1-d array, not a "column" nor a "row"

If you to preserve the rank, you can use a size-1 slice:

In [13]:
c = a[:, 2:3] # all rows, columns 2 to 3 (i.e only column 2)
print c
print c.shape

[[ 2]
 [ 7]
 [12]
 [17]]
(4, 1)


So still 2-d, but a single column: a "column vector" in linear algebra.

## Slice is a view

It's a new array, but a view on the data held by that array

Kinda-sorta like a shallow copy with lists, etc.

Here are some tests to see what's going on

In [13]:
# create an array:
a = np.arange(12, dtype=np.int32)
print_info(a)

arr :
[ 0  1  2  3  4  5  6  7  8  9 10 11]
arr.shape: (12,)
arr.dtype: int32
arr.itemsize 4
arr.ndim: 1
arr.strides (4,)
arr.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [16]:
# A slice is a view: (look at the OWNDATA flag)
b = a[3:6]
print(b)
print_info(b, 'b')

[3 4 5]
b :
[3 4 5]
b.shape: (3,)
b.dtype: int32
b.itemsize 4
b.ndim: 1
b.strides (4,)
b.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [17]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[3 4 5]


In [18]:
b[1] = 35
print(b)

[ 3 35  5]


In [19]:
a

array([ 0,  1,  2,  3, 35,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [20]:
# note "OWNDATA" flag -- b does not "own" its data.

b[0] = 44

print(b)
print(a)

# a has changed!

[44 35  5]
[ 0  1  2 44 35  5  6  7  8  9 10 11]


In [21]:
# what about slicing higher-dim arrays:
a = np.arange(12).reshape(3,4)
print_info(a,'a')

a :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.shape: (3, 4)
a.dtype: int64
a.itemsize 8
a.ndim: 2
a.strides (32, 8)
a.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [22]:
# "column" slice:
b = a[:,1]
print_info(b,'b')

b :
[1 5 9]
b.shape: (3,)
b.dtype: int64
b.itemsize 8
b.ndim: 1
b.strides (32,)
b.flags:
   C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [23]:
a[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a.shape


(3, 4)

In [25]:
# "row" slice:
b = a[1,:]
print_info(b,'b')

b :
[4 5 6 7]
b.shape: (4,)
b.dtype: int64
b.itemsize 8
b.ndim: 1
b.strides (8,)
b.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [26]:
a = np.arange(12)

In [27]:
a.shape = (3,4)

In [28]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b = a.reshape((4,3)).copy()

In [30]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a[2,2] = 0


In [33]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0, 11]])

In [34]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])