Intro to numpy broadcasting
-----------------------------

In [28]:
import numpy as np

In [29]:
a = np.ones((3,4))

In [30]:
print a

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [31]:
# the multiplication is "broadcast" over the whole array:
print a * 3

[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]


This is core of "vectorization" -- doing operations over a whole array at the speed of C -- key to numpy performance.

Regular python lists and comprehensions:

In [32]:
l = range(10000)

In [33]:
# using regular python list comprehensions
%timeit [i*3 for i in l]

1000 loops, best of 3: 568 µs per loop


Now the numpy way:

In [7]:
a = np.arange(10000) # create an array

In [34]:
timeit a * 3

The slowest run took 21.25 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.03 µs per loop


### in-place operations

One of the primary reasons "augemented assignemnt" was added to Python 
is support in-place operations:
    `+=`, `*=`, etc...

In [42]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a+=3
print a

[ 3  4  5  6  7  8  9 10 11 12]


A was changed in place -- no new memory allocation, loop at the speed of C.

How do you broadcast to multiple dimensions?

In [12]:
x = np.linspace(0,10,4)
y = np.linspace(100,200,3)

x.shape = (1, -1)
y.shape = (-1, 1)

print x


[[  0.           3.33333333   6.66666667  10.        ]]


In [13]:
print y

[[ 100.]
 [ 150.]
 [ 200.]]


In [14]:
a = np.arange(4)
print a  * x

[[  0.           3.33333333  13.33333333  30.        ]]


In [15]:
print a * y

[[   0.  100.  200.  300.]
 [   0.  150.  300.  450.]
 [   0.  200.  400.  600.]]


In [16]:
print np.sqrt(x**2 * y**2)

[[    0.           333.33333333   666.66666667  1000.        ]
 [    0.           500.          1000.          1500.        ]
 [    0.           666.66666667  1333.33333333  2000.        ]]
