Assorted numpy Constructors
-----------------------------

In [1]:
#Always need to import it... 
import numpy as np

In [6]:
# from scratch:
a = np.ones((3,2)) # default dtype is float64

In [7]:
a.dtype


dtype('float64')

In [9]:
print np.zeros((2,3), dtype=np.int32)

[[0 0 0]
 [0 0 0]]


In [10]:
print np.empty((3,3), dtype=np.float32) # not initilized!

[[  0.00000000e+00   2.00000000e+00   2.59846197e-29]
 [  2.00000000e+00   4.40810942e-39   1.40129846e-45]
 [  4.47912162e-39   1.40129846e-45   1.81219953e-37]]


In [13]:
# for a range:
# integers (much like the regular range...)
print np.arange(2, 10, .5)

[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.
  9.5]


In [15]:
# for floats
# from zero to 1  (inclusive)
# you want 11 total elements
print np.linspace(0, 1).shape

(50,)


In [12]:
# you can do arange with floats, too
# but it can get wierd with floating point error!
print np.arange(0,1.1, 0.1, dtype=np.float)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [16]:
# if you are a math/scicnce geek, adn want a log axis...
print np.logspace(0, 3, 4)

[    1.    10.   100.  1000.]


In [23]:
# from existing data:
# maybe the most common constructor 
a = np.array([(1, 2),
                (3, 4.0),
                (5, 6)]) # auto-determined dtype
print a

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [24]:
a.shape

(3, 2)

In [25]:
# maybe an array?
a = np.arange(5)
b = np.asarray(a)
print a is b

True


In [26]:
#or not:
a = range(5)
b = np.asarray(a)
print a is b

False


In [19]:
print np.ascontiguousarray(a)# forces contiguous datablock

[0 1 2 3 4]


In [20]:
# from binary data:
s = b'abcdefg'
a = np.frombuffer(s, dtype=np.uint8)
print a

[ 97  98  99 100 101 102 103]


In [21]:
print np.fromstring('\x12\x04', dtype=np.uint8) # really should be bytes...

[18  4]


In [27]:
# from (and to) binary file:
a = np.arange(5, dtype=np.float32) # jsut a binary dump!
a.tofile('junk.dat')

In [29]:
print np.fromfile('junk.dat', dtype=np.int32) # need dtype!

[         0 1065353216 1073741824 1077936128 1082130432]
