Assorted numpy Constructors
-----------------------------

In [4]:
#Always need to import it... 
import numpy as np

In [5]:
# from scratch:
print np.ones((3,)) # default dtype is float64

[ 1.  1.  1.]


In [6]:
print np.zeros((2,3), dtype=np.int32)

[[0 0 0]
 [0 0 0]]


In [7]:
print np.empty((3,3), dtype=np.float32) # not initilized!

[[  0.00000000e+00   4.65661287e-10   0.00000000e+00]
 [  4.65661287e-10   4.49994492e-39   1.40129846e-45]
 [  4.52125026e-39   1.40129846e-45   3.84062502e-38]]


In [8]:
# for a range:
# integers (much like the regular range...)
print np.arange(10)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# for floats
# from zero to 1  (inclusive)
# you want 11 total elements
print np.linspace(0, 1, 11)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [12]:
# you can do arange with floats, too
# but it can get wierd with floating point error!
print np.arange(0,1.1, 0.1, dtype=np.float)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [13]:
# if you are a math/scicnce geek, adn want a log axis...
print np.logspace(0, 3, 4)

[    1.    10.   100.  1000.]


In [16]:
# from existing data:
# maybe the most common constructor 
print np.array([(1, 2),
                (3, 4.0),
                (5, 6)]) # auto-determined dtype

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]


In [17]:
# maybe an array?
a = np.arange(5)
b = np.asarray(a)
print a is b

True


In [18]:
#or not:
a = range(5)
b = np.asarray(a)
print a is b

False


In [19]:
print np.ascontiguousarray(a)# forces contiguous datablock

[0 1 2 3 4]


In [20]:
# from binary data:
s = b'abcdefg'
a = np.frombuffer(s, dtype=np.uint8)
print a

[ 97  98  99 100 101 102 103]


In [21]:
print np.fromstring('\x12\x04', dtype=np.uint8) # really should be bytes...

[18  4]


In [22]:
# from (and to) binary file:
a = np.arange(5, dtype=np.float32) # jsut a binary dump!
a.tofile('junk.dat')

In [23]:
print np.fromfile('junk.dat', dtype=np.float32) # need dtype!

[ 0.  1.  2.  3.  4.]
