# Fancy Indexing


Fancy indexing is the name for when an array or list is used in-place of an index:

In [6]:
import numpy as np

In [8]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [7]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [9]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

We can also index masks: If the index mask is an Numpy array of with data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position each element:

In [12]:
B = np.arange(5)
B

array([0, 1, 2, 3, 4])

In [14]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [15]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])


This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [20]:
x = np.linspace(0, 5, 11)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [23]:
mask = (1.5 < x) * (x < 4.5)
mask

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False], dtype=bool)

## Functions for extracting data from arrays and creating arrays

### where
The index mask can be converted to position index using the where function

In [25]:
indices = np.where(mask)
indices

(array([4, 5, 6, 7, 8]),)