In [1]:
from start import *

Reshaping

In [27]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a.shape

(12,)

In [29]:
b = np.reshape(a, (3,4) )
print b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
b is a

False

In [31]:
# unknown dimension
a.shape = ( -1, 2)
print a

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [32]:
# flatten
for i in a.flat: # iterator
    print i 

0
1
2
3
4
5
6
7
8
9
10
11


In [33]:
b = np.ravel(a)
b
b is a

False

In [34]:
print a.shape
print a.T


(6, 2)
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [41]:
a.T.copy().ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Checking dimensions:

In [44]:
a = np.atleast_2d(a)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [46]:
a.shape

(1, 12)

In [48]:
# reducing:
a.shape = (2,1,1,6,1)
a.shape

(2, 1, 1, 6, 1)

In [49]:
b = np.squeeze(a)
b.shape

(2, 6)

In [50]:
# re-arranging:
print b
print np.flipud(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [51]:
print np.fliplr(b)

[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]]
